# Generated by Django 3.2.7 on 2021-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_alter_comics_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='comics',
            name='views',
        ),
        migrations.AddField(
            model_name='comics',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='comics.Ip'),
        ),
    ]
